### ISSUE TITLE
TypeError: 'type' object is not subscriptable 

### ISSUE THREAD

**Issue by MasoudRahmani** [An0nimia/DeezSpot_bot#51]
I cant run the program.

when I try to run with python 3.9 the is my error
```
Traceback (most recent call last):
  File "/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/deez_bot.py", line 3, in <module>
    from utils.utils import check_config_bot, show_menu
  File "/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/utils/utils.py", line 11, in <module>
    from deezloader.spotloader.spotify_settings import qualities as spo_qualities
  File "/home/hesam/.local/lib/python3.9/site-packages/deezloader/spotloader/__init__.py", line 5, in <module>
    from librespot.core import Session
ModuleNotFoundError: No module named 'librespot'

```

even though, librespot is installed.
```
hesam@zeus:/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot$ python3.9 -m pip install librespot
Requirement already satisfied: librespot in /home/hesam/.local/lib/python3.9/site-packages (0.0.0)
Requirement already satisfied: pycryptodome in /home/hesam/.local/lib/python3.9/site-packages (from librespot) (3.13.0)
Requirement already satisfied: protobuf in /home/hesam/.local/lib/python3.9/site-packages (from librespot) (3.19.3)
Requirement already satisfied: requests in /home/hesam/.local/lib/python3.9/site-packages (from librespot) (2.25.0)
Requirement already satisfied: defusedxml in /home/hesam/.local/lib/python3.9/site-packages (from librespot) (0.7.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->librespot) (2.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->librespot) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->librespot) (2019.11.28)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/hesam/.local/lib/python3.9/site-packages (from requests->librespot) (1.26.8)
hesam@zeus:/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot$
```

and when it is run with python3.8 I get this error

```
Traceback (most recent call last):
  File "deez_bot.py", line 3, in <module>
    from utils.utils import check_config_bot, show_menu
  File "/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/utils/utils.py", line 9, in <module>
    from deezloader.libutils.utils import var_excape
  File "/home/hesam/.local/lib/python3.8/site-packages/deezloader/__init__.py", line 3, in <module>
    from .__dee_api__ import API
  File "/home/hesam/.local/lib/python3.8/site-packages/deezloader/__dee_api__.py", line 6, in <module>
    from .__utils__ import artist_sort, convert_to_date
  File "/home/hesam/.local/lib/python3.8/site-packages/deezloader/__utils__.py", line 5, in <module>
    from .models.track import Track
  File "/home/hesam/.local/lib/python3.8/site-packages/deezloader/models/__init__.py", line 3, in <module>
    from .smart import Smart
  File "/home/hesam/.local/lib/python3.8/site-packages/deezloader/models/smart.py", line 4, in <module>
    from .album import Album
  File "/home/hesam/.local/lib/python3.8/site-packages/deezloader/models/album.py", line 5, in <module>
    class Album:
  File "/home/hesam/.local/lib/python3.8/site-packages/deezloader/models/album.py", line 19, in Album
    def tracks(self) -> list[Track]:
TypeError: 'type' object is not subscriptable

```

**Comment by An0nimia** [comment]
@MasoudRahmani sorry this is a my imprecision, search on google librespot python and you will that you need to install the version present on git and not the one on pypi

**Comment by MasoudRahmani** [comment]
Oh, thanks.
installing pip install with this code
` python3.9 -m pip install git+https://github.com/kokarare1212/librespot-python`
solved it.
