### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by MasoudRahmani** [An0nimia/DeezSpot_bot#54]
Should I use absolute path for db too? (but I cant find the db file, or is it not created?

```
Traceback (most recent call last):
  File "/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/deez_bot.py", line 5, in <module>
    check_config_bot()
  File "/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/utils/utils.py", line 230, in check_config_bot
    initialize_db()
  File "/home/vlaw/tlgrmBot/deezspot/DeezloaderBIB_bot/helpers/db_help.py", line 38, in initialize_db
    con = db_connect(db_name)
sqlite3.OperationalError: unable to open database file

```

**Comment by An0nimia** [comment]
@MasoudRahmani man just open a terminal in the project folder

**Comment by MasoudRahmani** [comment]
did that, doesn't work
![image](https://user-images.githubusercontent.com/5321268/151167913-1c5c5e6d-418f-4c73-8e39-3fdf7a90d73a.png)

**Comment by An0nimia** [comment]
@MasoudRahmani delete the db file and restart the script
